
-- Artifact locations
ARTIFACT_LOCATION_BACKPACK = 0
ARTIFACT_LOCATION_BODY = 1
ARTIFACT_LOCATION_HEAD = 2
ARTIFACT_LOCATION_RIGHTHAND = 3
ARTIFACT_LOCATION_LEFTHAND = 4
ARTIFACT_LOCATION_LEGS = 5
ARTIFACT_LOCATION_SHOULDERS = 6
ARTIFACT_LOCATION_RING = 7
ARTIFACT_LOCATION_NECK = 8
ARTIFACT_LOCATION_POCKET = 9

-- Artifact sets
ARTIFACT_SET_HAVEN = 1
ARTIFACT_SET_SYLVAN = 2
ARTIFACT_SET_ACADEMY = 3
ARTIFACT_SET_DWARVEN = 4
ARTIFACT_SET_NECRO = 5
ARTIFACT_SET_INFERNO = 6
ARTIFACT_SET_DUNGEON = 7
ARTIFACT_SET_ORCS = 8
ARTIFACT_SET_DRAGON = 9
ARTIFACT_SET_ENLIGHTEN = 10

-- Artifacts
ARTIFACT_SWORD_OF_RUINS = 1
ARTIFACT_GREAT_AXE_OF_GIANT_SLAYING = 2
ARTIFACT_WAND_OF_X = 3
ARTIFACT_UNICORN_HORN_BOW = 4
ARTIFACT_TITANS_TRIDENT = 5
ARTIFACT_STAFF_OF_VEXINGS = 6
ARTIFACT_SHACKLES_OF_WAR = 7
ARTIFACT_FOUR_LEAF_CLOVER = 8
ARTIFACT_ICEBERG_SHIELD = 9
ARTIFACT_GOLDEN_SEXTANT = 10
ARTIFACT_CROWN_OF_COURAGE = 11
ARTIFACT_CROWN_OF_MANY_EYES = 12
ARTIFACT_PLATE_MAIL_OF_STABILITY = 13
ARTIFACT_BREASTPLATE_OF_PETRIFIED_WOOD = 14
ARTIFACT_PEDANT_OF_MASTERY = 15
ARTIFACT_NECKLACE_OF_BRAVERY = 16
ARTIFACT_WEREWOLF_CLAW_NECKLACE = 17
ARTIFACT_EVERCOLD_ICICLE = 18
ARTIFACT_NECKLACE_OF_POWER = 19
ARTIFACT_RING_OF_LIGHTING_PROTECTION = 20
ARTIFACT_RING_OF_LIFE = 21
ARTIFACT_RING_OF_HASTE = 22
ARTIFACT_NIGHTMARISH_RING = 23
ARTIFACT_BOOTS_OF_SPEED = 24
ARTIFACT_GOLDEN_HORSESHOE = 25
ARTIFACT_WAYFARER_BOOTS = 26
ARTIFACT_BOOTS_OF_INTERFERENCE = 27
ARTIFACT_ENDLESS_SACK_OF_GOLD = 28
ARTIFACT_ENDLESS_BAG_OF_GOLD = 29
ARTIFACT_ANGEL_WINGS = 30
ARTIFACT_LION_HIDE_CAPE = 31
ARTIFACT_PHOENIX_FEATHER_CAPE = 32
ARTIFACT_CLOAK_OF_MOURNING = 33
ARTIFACT_HELM_OF_ENLIGHTMENT = 34
ARTIFACT_CHAIN_MAIL_OF_ENLIGHTMENT = 35
ARTIFACT_DRAGON_SCALE_ARMOR = 36
ARTIFACT_DRAGON_SCALE_SHIELD = 37
ARTIFACT_DRAGON_BONE_GRAVES = 38
ARTIFACT_DRAGON_WING_MANTLE = 39
ARTIFACT_DRAGON_TEETH_NECKLACE = 40
ARTIFACT_DRAGON_TALON_CROWN = 41
ARTIFACT_DRAGON_EYE_RING = 42
ARTIFACT_DRAGON_FLAME_TONGUE = 43
ARTIFACT_ROBE_OF_MAGI = 44
ARTIFACT_STAFF_OF_MAGI = 45
ARTIFACT_CROWN_OF_MAGI = 46
ARTIFACT_RING_OF_MAGI = 47
ARTIFACT_DWARVEN_MITHRAL_CUIRASS = 48
ARTIFACT_DWARVEN_MITHRAL_GREAVES = 49
ARTIFACT_DWARVEN_MITHRAL_HELMET = 50
ARTIFACT_DWARVEN_MITHRAL_SHIELD = 51
ARTIFACT_SCROLL_OF_SPELL_X = 52
ARTIFACT_GRAAL = 53
ARTIFACT_BOOTS_OF_LEVITATION = 54
ARTIFACT_SKULL_HELMET = 55
ARTIFACT_VALORIOUS_ARMOR = 56
ARTIFACT_BOOTS_OF_SWIFTNESS = 57
ARTIFACT_MOONBLADE = 58
ARTIFACT_RING_OF_CELERITY = 59
ARTIFACT_BAND_OF_CONJURER = 60
ARTIFACT_EARTHSLIDERS = 61
ARTIFACT_RIGID_MANTLE = 62
ARTIFACT_JINXING_BAND = 63
ARTIFACT_BONESTUDDED_LEATHER = 64
ARTIFACT_WISPERING_RING = 65
ARTIFACT_HELM_OF_CHAOS = 66
ARTIFACT_TWISTING_NEITHER = 67
ARTIFACT_SANDALS_OF_THE_SAINT = 68
ARTIFACT_SHAWL_OF_GREAT_LICH = 69
ARTIFACT_RING_OF_DEATH = 70
ARTIFACT_NECROMANCER_PENDANT = 71
ARTIFACT_FREIDA = 72
ARTIFACT_RING_OF_THE_SHADOWBRAND = 73
ARTIFACT_OGRE_CLUB = 74
ARTIFACT_OGRE_SHIELD = 75
ARTIFACT_TOME_OF_DESTRUCTION = 76
ARTIFACT_TOME_OF_LIGHT_MAGIC = 77
ARTIFACT_TOME_OF_DARK_MAGIC = 78
ARTIFACT_TOME_OF_SUMMONING_MAGIC = 79
ARTIFACT_BEGINNER_MAGIC_STICK = 80
ARTIFACT_RUNIC_WAR_AXE = 81
ARTIFACT_RUNIC_WAR_HARNESS = 82
ARTIFACT_SKULL_OF_MARKAL = 83
ARTIFACT_BEARHIDE_WRAPS = 84
ARTIFACT_DWARVEN_SMITHY_HUMMER = 85
ARTIFACT_RUNE_OF_FLAME = 86
ARTIFACT_TAROT_DECK = 87
ARTIFACT_CROWN_OF_LEADER = 88
ARTIFACT_MASK_OF_DOPPELGANGER = 89
ARTIFACT_EDGE_OF_BALANCE = 90
ARTIFACT_RING_OF_MACHINE_AFFINITY = 91
ARTIFACT_HORN_OF_PLENTY = 92
ARTIFACT_RING_OF_UNSUMMONING = 93
ARTIFACT_BOOK_OF_POWER = 94
ARTIFACT_TREEBORN_QUIVER = 95
ARTIFACT_PRINCESS = 96
ARTIFACT_RES_WOOD = 97
ARTIFACT_RES_ORE = 98
ARTIFACT_RES_SULPHUR = 99
ARTIFACT_RES_CRYSTAL = 100
ARTIFACT_RES_GEM = 101
ARTIFACT_RES_MERCURY = 102	
ARTIFACT_LEGION_T1 = 103
ARTIFACT_LEGION_T2 = 104
ARTIFACT_LEGION_T3 = 105
ARTIFACT_LEGION_T4 = 106
ARTIFACT_LEGION_T5 = 107
ARTIFACT_LEGION_T6 = 108
ARTIFACT_LEGION_T7 = 109
ARTIFACT_STEADFAST = 110
ARTIFACT_BUCKLER = 111
ARTIFACT_LIFE_01 = 112
ARTIFACT_LIFE_02 = 113
ARTIFACT_LIFE_03 = 114
ARTIFACT_LIFE_04 = 115
ARTIFACT_MONK_01 = 116
ARTIFACT_MONK_02 = 117
ARTIFACT_MONK_03 = 118
ARTIFACT_MONK_04 = 119
ARTIFACT_GUARDIAN_01 = 120
ARTIFACT_GUARDIAN_02 = 121
ARTIFACT_GUARDIAN_03 = 122
ARTIFACT_DRACONIC = 123
ARTIFACT_SENTINEL = 124
ARTIFACT_EIGHTFOLD = 125
ARTIFACT_CODEX = 126
ARTIFACT_PIRATE01 = 127
ARTIFACT_PIRATE02 = 128
ARTIFACT_PIRATE03 = 129
ARTIFACT_PIRATE04 = 130
ARTIFACT_PIRATE05 = 131
ARTIFACT_PIRATE06 = 132	
ARTIFACT_MEDICAL01 = 133
ARTIFACT_MEDICAL02 = 134
ARTIFACT_MEDICAL03 = 135
ARTIFACT_MEDICAL04 = 136
ARTIFACT_POTION01 = 137	
ARTIFACT_POTION02 = 138		
ARTIFACT_POTION03 = 139
ARTIFACT_BOOK_A1 = 140
ARTIFACT_BOOK_A2 = 141
ARTIFACT_BOOK_A3 = 142
ARTIFACT_BOOK_A4 = 143
ARTIFACT_BOOK_D1 = 144
ARTIFACT_BOOK_D2 = 145
ARTIFACT_BOOK_D3 = 146
ARTIFACT_BOOK_D4 = 147
ARTIFACT_BOOK_S1 = 148
ARTIFACT_BOOK_S2 = 149
ARTIFACT_BOOK_S3 = 150
ARTIFACT_BOOK_S4 = 151
ARTIFACT_BOOK_K1 = 152
ARTIFACT_BOOK_K2 = 153
ARTIFACT_BOOK_K3 = 154
ARTIFACT_BOOK_K4 = 155
ARTIFACT_BOOK_R1 = 156	
ARTIFACT_BOOK_R2 = 157	
ARTIFACT_BOOK_R3 = 158	
ARTIFACT_SHANTIRI_01 = 159	
ARTIFACT_SHANTIRI_02 = 160	
ARTIFACT_SHANTIRI_03 = 161	
ARTIFACT_SHANTIRI_04 = 162	
ARTIFACT_SHANTIRI_05 = 163	
ARTIFACT_UPG_AR1 = 164	
ARTIFACT_UPG_AR2 = 165
ARTIFACT_UPG_AR3 = 166	
ARTIFACT_UPG_HM1 = 167	
ARTIFACT_UPG_HM2 = 168
ARTIFACT_UPG_HM3 = 169
ARTIFACT_UPG_ST1 = 170
ARTIFACT_UPG_ST2 = 171
ARTIFACT_UPG_ST3 = 172
ARTIFACT_UPG_SW1 = 173	
ARTIFACT_UPG_SW2 = 174
ARTIFACT_UPG_SW3 = 175	
ARTIFACT_FIZBIN = 176
ARTIFACT_FORGING = 177				
ARTIFACT_URGASH_01 = 178	
ARTIFACT_URGASH_02 = 179
ARTIFACT_ELRATH_01 = 180		
ARTIFACT_ELRATH_02 = 181	
ARTIFACT_GOVERNOR_01 = 182
ARTIFACT_GOVERNOR_02 = 183				
ARTIFACT_GEAR_01 = 184
ARTIFACT_GEAR_02 = 185
ARTIFACT_GEAR_03 = 186
ARTIFACT_GEAR_04 = 187
ARTIFACT_GEAR_05 = 188	
ARTIFACT_GEAR_06 = 189	
ARTIFACT_GEAR_07 = 190	
ARTIFACT_GEAR_08 = 191	
ARTIFACT_ORB_01 = 192
ARTIFACT_ORB_02 = 193
ARTIFACT_ORB_03	= 194
ARTIFACT_ORB_04 = 195


ARTIFACT_LOCATIONS = {
    [ARTIFACT_LOCATION_BACKPACK] = {},
    [ARTIFACT_LOCATION_BODY] = {ARTIFACT_PLATE_MAIL_OF_STABILITY, ARTIFACT_BREASTPLATE_OF_PETRIFIED_WOOD, ARTIFACT_CHAIN_MAIL_OF_ENLIGHTMENT, ARTIFACT_DRAGON_SCALE_ARMOR, ARTIFACT_ROBE_OF_MAGI, ARTIFACT_DWARVEN_MITHRAL_CUIRASS, },
    [ARTIFACT_LOCATION_HEAD] = {ARTIFACT_CROWN_OF_COURAGE, ARTIFACT_CROWN_OF_MANY_EYES, ARTIFACT_HELM_OF_ENLIGHTMENT, ARTIFACT_DRAGON_TALON_CROWN, ARTIFACT_CROWN_OF_MAGI, ARTIFACT_DWARVEN_MITHRAL_HELMET, },
    [ARTIFACT_LOCATION_RIGHTHAND] = {ARTIFACT_SWORD_OF_RUINS, ARTIFACT_GREAT_AXE_OF_GIANT_SLAYING, ARTIFACT_TITANS_TRIDENT, ARTIFACT_STAFF_OF_VEXINGS, ARTIFACT_DRAGON_FLAME_TONGUE, ARTIFACT_STAFF_OF_MAGI, },
    [ARTIFACT_LOCATION_LEFTHAND] = {ARTIFACT_ICEBERG_SHIELD, ARTIFACT_DRAGON_SCALE_SHIELD, ARTIFACT_DWARVEN_MITHRAL_SHIELD, ARTIFACT_SCROLL_OF_SPELL_X, },
    [ARTIFACT_LOCATION_LEGS] = {ARTIFACT_BOOTS_OF_SPEED, ARTIFACT_WAYFARER_BOOTS, ARTIFACT_BOOTS_OF_INTERFERENCE, ARTIFACT_DRAGON_BONE_GRAVES, ARTIFACT_DWARVEN_MITHRAL_GREAVES, },
    [ARTIFACT_LOCATION_SHOULDERS] = {ARTIFACT_ENDLESS_BAG_OF_GOLD, ARTIFACT_ANGEL_WINGS, ARTIFACT_LION_HIDE_CAPE, ARTIFACT_PHOENIX_FEATHER_CAPE, ARTIFACT_CLOAK_OF_MOURNING, ARTIFACT_DRAGON_WING_MANTLE, },
    [ARTIFACT_LOCATION_RING] = {ARTIFACT_RING_OF_LIGHTING_PROTECTION, ARTIFACT_RING_OF_LIFE, ARTIFACT_RING_OF_HASTE, ARTIFACT_NIGHTMARISH_RING, ARTIFACT_DRAGON_EYE_RING, ARTIFACT_RING_OF_MAGI, },
    [ARTIFACT_LOCATION_NECK] = {ARTIFACT_PEDANT_OF_MASTERY, ARTIFACT_NECKLACE_OF_BRAVERY, ARTIFACT_WEREWOLF_CLAW_NECKLACE, ARTIFACT_EVERCOLD_ICICLE, ARTIFACT_NECKLACE_OF_POWER, ARTIFACT_DRAGON_TEETH_NECKLACE},
    [ARTIFACT_LOCATION_POCKET] = {ARTIFACT_SHACKLES_OF_WAR, ARTIFACT_FOUR_LEAF_CLOVER, ARTIFACT_GOLDEN_SEXTANT, ARTIFACT_GOLDEN_HORSESHOE, ARTIFACT_ENDLESS_SACK_OF_GOLD, },
}

ARTIFACT_SETS = {
    [ARTIFACT_SET_HAVEN] = {ARTIFACT_NECKLACE_OF_BRAVERY,ARTIFACT_CROWN_OF_COURAGE,ARTIFACT_LION_HIDE_CAPE},
    [ARTIFACT_SET_SYLVAN] = {ARTIFACT_UNICORN_HORN_BOW,ARTIFACT_TREEBORN_QUIVER},
    [ARTIFACT_SET_ACADEMY] = {ARTIFACT_ROBE_OF_MAGI,ARTIFACT_STAFF_OF_MAGI,ARTIFACT_CROWN_OF_MAGI,ARTIFACT_RING_OF_MAGI},
    [ARTIFACT_SET_DWARVEN] = {ARTIFACT_DWARVEN_MITHRAL_CUIRASS,ARTIFACT_DWARVEN_MITHRAL_GREAVES,ARTIFACT_DWARVEN_MITHRAL_HELMET,ARTIFACT_DWARVEN_MITHRAL_SHIELD},
    [ARTIFACT_SET_NECRO] = {ARTIFACT_STAFF_OF_VEXINGS,ARTIFACT_SHAWL_OF_GREAT_LICH,ARTIFACT_RING_OF_DEATH,ARTIFACT_NECROMANCER_PENDANT},
    [ARTIFACT_SET_INFERNO] = {},
    [ARTIFACT_SET_DUNGEON] = {ARTIFACT_RUNIC_WAR_AXE,ARTIFACT_RUNIC_WAR_HARNESS},
    [ARTIFACT_SET_ORCS] = {ARTIFACT_OGRE_CLUB,ARTIFACT_OGRE_SHIELD},
    [ARTIFACT_SET_DRAGON]= {ARTIFACT_DRAGON_SCALE_ARMOR,ARTIFACT_DRAGON_SCALE_SHIELD,ARTIFACT_DRAGON_BONE_GRAVES,ARTIFACT_DRAGON_WING_MANTLE,ARTIFACT_DRAGON_TEETH_NECKLACE,ARTIFACT_DRAGON_TALON_CROWN,ARTIFACT_DRAGON_EYE_RING,ARTIFACT_DRAGON_FLAME_TONGUE},
    [ARTIFACT_SET_ENLIGHTEN] = {ARTIFACT_HELM_OF_ENLIGHTMENT,ARTIFACT_CHAIN_MAIL_OF_ENLIGHTMENT},
}

ARTIFACT_SETS_ACTIVATIONS = {
    [ARTIFACT_SET_HAVEN] = {[2]=ARTFSET_HAVEN_2PC, [4]=ARTFSET_HAVEN_4PC, [6]=ARTFSET_HAVEN_6PC, [8]=ARTFSET_HAVEN_8PC},
    [ARTIFACT_SET_SYLVAN] = {[2]=ARTFSET_SYLVAN_2PC, [4]=ARTFSET_SYLVAN_4PC, [6]=ARTFSET_SYLVAN_6PC, [8]=ARTFSET_SYLVAN_8PC},
    [ARTIFACT_SET_ACADEMY] = {[2]=ARTFSET_ACADEMY_2PC, [4]=ARTFSET_ACADEMY_4PC, [6]=ARTFSET_ACADEMY_6PC, [8]=ARTFSET_ACADEMY_8PC},
    [ARTIFACT_SET_DWARVEN] = {[2]=ARTFSET_DWARVEN_2PC, [4]=ARTFSET_DWARVEN_4PC, [6]=ARTFSET_DWARVEN_6PC, [8]=ARTFSET_DWARVEN_8PC},
    [ARTIFACT_SET_NECRO] = {[2]=ARTFSET_NECRO_2PC, [4]=ARTFSET_NECRO_4PC, [6]=ARTFSET_NECRO_6PC, [8]=ARTFSET_NECRO_8PC},
    [ARTIFACT_SET_INFERNO] = {[2]=ARTFSET_INFERNO_2PC, [4]=ARTFSET_INFERNO_4PC, [6]=ARTFSET_INFERNO_6PC, [8]=ARTFSET_INFERNO_8PC},
    [ARTIFACT_SET_DUNGEON] = {[2]=ARTFSET_DUNGEON_2PC, [4]=ARTFSET_DUNGEON_4PC, [6]=ARTFSET_DUNGEON_6PC, [8]=ARTFSET_DUNGEON_8PC},
    [ARTIFACT_SET_ORCS] = {[2]=ARTFSET_ORCS_2PC, [4]=ARTFSET_ORCS_4PC, [6]=ARTFSET_ORCS_6PC, [8]=ARTFSET_ORCS_8PC},
    [ARTIFACT_SET_DRAGON]= {[2]=ARTFSET_DRAGON_2PC, [4]=ARTFSET_DRAGON_4PC, [6]=ARTFSET_DRAGON_6PC, [8]=ARTFSET_DRAGON_8PC},
    [ARTIFACT_SET_ENLIGHTEN] = {[2]=ARTFSET_ENLIGHTEN_2PC, [4]=ARTFSET_ENLIGHTEN_4PC},
}


-- print("Loaded artifact advmap routines")
ROUTINES_LOADED[12] = 1
