-- Global symbols (DO NOT EDIT)
	dofile = doFile

	dofile('/scripts/events.lua')

	--
	-- Logical constants
	--
	true = not nil
	false = nil

	--
	-- Names filter
	--
	FILTER_HEROES = 0
	FILTER_OBJECTS = 1
	FILTER_REGIONS = 2
	FILTER_OBJECTIVES = 3

    --
    -- Player IDs
    --
	PLAYER_NONE = 0
	PLAYER_1 = 1
	PLAYER_2 = 2
	PLAYER_3 = 3
	PLAYER_4 = 4
	PLAYER_5 = 5
	PLAYER_6 = 6
	PLAYER_7 = 7
	PLAYER_8 = 8

	--
	-- Player states
	--
	PLAYER_NOT_IN_GAME = 0
	PLAYER_ACTIVE = 1
	PLAYER_WON = 2
	PLAYER_LOST = 3

	--
	-- Floors names
	--
	GROUND = 0
	UNDERGROUND = 1

	--
	-- Kinds of resources
	--
	WOOD    = 0
	ORE     = 1
	MERCURY = 2
	CRYSTAL = 3
	SULFUR  = 4
	GEM     = 5
	GOLD    = 6

	RESOURCE_TEXT = {
		[0] = "Wood",
		[1] = "Ore",
		[2] = "Mercury",
		[3] = "Cystal",
		[4] = "Sulfur",
		[5] = "Gem",
		[6] = "Golds"
	}
	
	--
	-- Kinds of treasures
	--
	TREASURE_CRYSTAL   = 0
	TREASURE_GEMS      = 1
	TREASURE_GOLD      = 2
	TREASURE_MERCURY   = 3
	TREASURE_ORE       = 4
	TREASURE_SULFUR    = 5
	TREASURE_WOOD      = 6
	TREASURE_CAMPFIRE  = 8
	TREASURE_CHEST     = 9
	TREASURE_SEA_CHEST = 10
	TREASURE_FLOATSAM  = 11
	TREASURE_SHIPWRECK = 13

    --
    -- Date type IDs
    --
    DAY = 0
    WEEK = 1
    MONTH = 2
    DAY_OF_WEEK = 3
    ABSOLUTE_DAY = DAY

	--
	-- Advmap predefided names
	--
	OBJECT_GRAIL = 'grail'

	--
	-- Advmap object types
	--
	OBJECT_HERO = 0

    --
    -- Hero stat`s IDs
    --
    STAT_EXPERIENCE = 0
    STAT_ATTACK = 1
    STAT_DEFENCE = 2
    STAT_SPELL_POWER = 3
    STAT_KNOWLEDGE = 4
    STAT_LUCK = 5
    STAT_MORALE = 6
    STAT_MOVE_POINTS = 7
    STAT_MANA_POINTS = 8

	ATTRIBUTE_TEXT = {
		[0] = "Experience",
		[1] = "Attack",
		[2] = "Defence",
		[3] = "Spellpower",
		[4] = "Knowledge",
		[5] = "Luck",
		[6] = "Morale",
		[7] = "Movement",
		[8] = "Mana"
	}
	
	--
	-- Objective state`s IDs
	--
	OBJECTIVE_SCENARIO_INFO = 0
	OBJECTIVE_UNKNOWN = 1
	OBJECTIVE_ACTIVE = 2
	OBJECTIVE_COMPLETED = 3
	OBJECTIVE_FAILED = 4


	--
	-- Town type IDs
	--
	TOWN_HEAVEN = 0
	TOWN_PRESERVE = 1
	TOWN_ACADEMY = 2
	TOWN_DUNGEON = 3
	TOWN_NECROMANCY = 4
	TOWN_INFERNO = 5
	TOWN_FORTRESS = 6
	TOWN_STRONGHOLD = 7

	--
	-- Town buildings IDs
	--
	TOWN_BUILDING_TOWN_HALL = 0
	TOWN_BUILDING_FORT = 1
	TOWN_BUILDING_MARKETPLACE = 2	
	TOWN_BUILDING_SHIPYARD = 3
	TOWN_BUILDING_TAVERN = 4
	TOWN_BUILDING_BLACKSMITH = 5
	TOWN_BUILDING_MAGIC_GUILD = 6
	TOWN_BUILDING_DWELLING_1 = 7
	TOWN_BUILDING_DWELLING_2 = 8
	TOWN_BUILDING_DWELLING_3 = 9
	TOWN_BUILDING_DWELLING_4 = 10
	TOWN_BUILDING_DWELLING_5 = 11
	TOWN_BUILDING_DWELLING_6 = 12
	TOWN_BUILDING_DWELLING_7 = 13
	TOWN_BUILDING_GRAIL = 14
	TOWN_BUILDING_WONDER = 15
	TOWN_BUILDING_SPECIAL_0 = 16
	TOWN_BUILDING_SPECIAL_1 = 17
	TOWN_BUILDING_SPECIAL_2 = 18
	TOWN_BUILDING_SPECIAL_3 = 19
	TOWN_BUILDING_SPECIAL_4 = 20
	TOWN_BUILDING_SPECIAL_5 = 21
	TOWN_BUILDING_SPECIAL_6 = 22
	TOWN_BUILDING_SPECIAL_7 = 23
	TOWN_BUILDING_SPECIAL_8 = 24
	TOWN_BUILDING_SPECIAL_9 = 25

	TOWN_BUILDING_HAVEN_TRAINING_GROUNDS 			= TOWN_BUILDING_SPECIAL_1
	TOWN_BUILDING_HAVEN_MONUMENT_TO_FALLEN_HEROES 	= TOWN_BUILDING_SPECIAL_2
	TOWN_BUILDING_HAVEN_HOSPITAL 					= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_HAVEN_STABLE 						= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_HAVEN_FARMS 						= TOWN_BUILDING_SPECIAL_5
	TOWN_BUILDING_INFERNO_INFERNAL_LOOM 			= TOWN_BUILDING_SPECIAL_1
	TOWN_BUILDING_INFERNO_ORDER_OF_FIRE 			= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_INFERNO_HALLS_OF_HORROR 			= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_INFERNO_SACRIFICIAL_PIT 			= TOWN_BUILDING_SPECIAL_5
	TOWN_BUILDING_DUNGEON_ALTAR_OF_ELEMENTS 		= TOWN_BUILDING_SPECIAL_1
	TOWN_BUILDING_DUNGEON_RITUAL_PIT 				= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_DUNGEON_TRADE_GUILD				= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_DUNGEON_TREASURE_DIG_SITE 		= TOWN_BUILDING_SPECIAL_5
	TOWN_BUILDING_DUNGEON_HALL_OF_INTRIGUE 			= TOWN_BUILDING_SPECIAL_6
	TOWN_BUILDING_ACADEMY_LIBRARY 					= TOWN_BUILDING_SPECIAL_1
	TOWN_BUILDING_ACADEMY_ARCANE_FORGE 				= TOWN_BUILDING_SPECIAL_2
	TOWN_BUILDING_ACADEMY_ARTIFACT_MERCHANT			= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_ACADEMY_TREASURE_CAVE 			= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_ACADEMY_ELEMENTAL_ENCLAVE 		= TOWN_BUILDING_SPECIAL_5
	TOWN_BUILDING_PRESERVE_AVENGERS_BROTHERHOOD		= TOWN_BUILDING_SPECIAL_0
	TOWN_BUILDING_PRESERVE_MYSTIC_POND 				= TOWN_BUILDING_SPECIAL_2
	TOWN_BUILDING_PRESERVE_SPARKLING_FONTAINS 		= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_PRESERVE_BLOOMING_GROVE 			= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_PRESERVE_TREANT_SAMPLING 			= TOWN_BUILDING_SPECIAL_5
	TOWN_BUILDING_NECROMANCY_AMPLIFIER 				= TOWN_BUILDING_SPECIAL_1
	TOWN_BUILDING_NECROMANCY_UNHOLY_TEMPLE 			= TOWN_BUILDING_SPECIAL_2
	TOWN_BUILDING_NECROMANCY_UNEARHED_GRAVES 		= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_NECROMANCY_DRAGON_TOMBSTONE 		= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_NECROMANCY_SHROUD_OF_DARKNESS 	= TOWN_BUILDING_SPECIAL_5
	TOWN_BUILDING_FORTRESS_RUNIC_SHRINE 			= TOWN_BUILDING_SPECIAL_1
	TOWN_BUILDING_FORTRESS_ARENA 					= TOWN_BUILDING_SPECIAL_2
	TOWN_BUILDING_FORTRESS_GUARDPOST 				= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_FORTRESS_RUNIC_STONEWORKS 		= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_FORTRESS_RUNIC_ACADEMY 			= TOWN_BUILDING_SPECIAL_5
	TOWN_BUILDING_STRONGHOLD_HALL_OF_TRIAL			= TOWN_BUILDING_SPECIAL_1
	TOWN_BUILDING_STRONGHOLD_GARBAGE_PILE			= TOWN_BUILDING_SPECIAL_2
	TOWN_BUILDING_STRONGHOLD_TRAVELLERS_SHELTER		= TOWN_BUILDING_SPECIAL_3
	TOWN_BUILDING_STRONGHOLD_PILE_OF_OUR_FOES		= TOWN_BUILDING_SPECIAL_4
	TOWN_BUILDING_STRONGHOLD_SLAVE_MARKET			= TOWN_BUILDING_SPECIAL_5

	--
	-- Monster mood IDs
	--
	MONSTER_MOOD_FRIENDLY = 0
	MONSTER_MOOD_AGGRESSIVE = 1
	MONSTER_MOOD_HOSTILE = 2
	MONSTER_MOOD_WILD = 3

	--
	-- Monster courage IDs
	--
	MONSTER_COURAGE_ALWAYS_JOIN = 0
	MONSTER_COURAGE_ALWAYS_FIGHT = 1
	MONSTER_COURAGE_CAN_FLEE_JOIN = 2

	--
	-- Borderguard key colors
	--
	RED_KEY = 1
	BLUE_KEY = 2
	GREEN_KEY = 3
	YELLOW_KEY = 4
	ORANGE_KEY = 5
	TEAL_KEY = 6
	PURPLE_KEY = 7
	TAN_KEY = 8

	--
	-- Trigger type IDs
	--
	NEW_DAY_TRIGGER = 0
	PLAYER_ADD_HERO_TRIGGER = 1
	PLAYER_REMOVE_HERO_TRIGGER = 2
	OBJECTIVE_STATE_CHANGE_TRIGGER = 3
	OBJECT_TOUCH_TRIGGER = 4
	OBJECT_CAPTURE_TRIGGER = 5
	REGION_ENTER_AND_STOP_TRIGGER = 6
	REGION_ENTER_WITHOUT_STOP_TRIGGER = 7
	HERO_LEVELUP_TRIGGER = 8
	WAR_FOG_ENTER_TRIGGER = 9
	COMBAT_RESULTS_TRIGGER = 11
	CUSTOM_ABILITY_TRIGGER = 12
	REGION_EXIT_TRIGGER = 13
	HERO_ADD_SKILL_TRIGGER = 14
	HERO_REMOVE_SKILL_TRIGGER = 15
	HERO_TOUCH_TRIGGER = 16  -- works only for heroes disabled by SetObjectEnabled function

	--
	-- Saved combat results types
	--
	COMBAT_RESULT_NONE = 0
	COMBAT_RESULT_WIN = 1
	COMBAT_RESULT_RETREAT = 2
	COMBAT_RESULT_SURRENDER = 3

	--
	-- Custom abilities IDs
	--
	CUSTOM_ABILITY_1 = 1
	CUSTOM_ABILITY_2 = 2
	CUSTOM_ABILITY_3 = 3
	CUSTOM_ABILITY_4 = 4

	--
	-- Custom abilities modes
	--
	CUSTOM_ABILITY_NOT_PRESENT = -1
	CUSTOM_ABILITY_DISABLED = 0
	CUSTOM_ABILITY_ENABLED = 1

	--
	-- Moon weeks (for GetCurrentMoonWeek adventure script function)
	--
	WEEK_OF_NOTHING = 0
	WEEK_OF_TOAD = 1
	WEEK_OF_SALAMANDER = 2
	WEEK_OF_BEETLE = 3
	WEEK_OF_WYVERN = 4
	WEEK_OF_DRAGONFLY = 5
	WEEK_OF_FOX = 6
	WEEK_OF_SHAMAN = 7
	WEEK_OF_RABBIT = 8
	WEEK_OF_SQUIRREL = 9
	WEEK_OF_CATERPILLAR = 10
	WEEK_OF_HAMSTER = 11
	WEEK_OF_PIGEON = 12
	WEEK_OF_RAGE = 13
	WEEK_OF_EAGLE = 14
	WEEK_OF_BEE = 15
	WEEK_OF_WASP = 16
	WEEK_OF_SWAN = 17
	WEEK_OF_BUTTERFLY = 18
	WEEK_OF_THANE = 19
	WEEK_OF_ANTILOPE = 20
	WEEK_OF_ORC = 21
	WEEK_OF_RAVEN = 22
	WEEK_OF_BADGER = 23
	WEEK_OF_FLAMINGO = 24
	WEEK_OF_TORTOISE = 25
	WEEK_OF_LYNX = 26
	WEEK_OF_PENGUIN = 27
	WEEK_OF_FALCON = 28
	WEEK_OF_HEDGEHOG = 29
	WEEK_OF_SPARROW = 30
	WEEK_OF_SWALLOW = 31
	WEEK_OF_LION = 32
	WEEK_OF_SPEARS = 33
	WEEK_OF_BEAR = 34
	WEEK_OF_CHIEFTAIN = 35
	WEEK_OF_CENTAUR = 36
	WEEK_OF_GOBLIN = 37
	WEEK_OF_DEER = 38
	WEEK_OF_OWL = 39
	WEEK_OF_DEFENDER = 40
	WEEK_OF_WYRM = 41
	WEEK_OF_TIGER = 42
	WEEK_OF_PLAGUE = 43
	WEEK_OF_DISEASE = 44
	WEEK_OF_FEVER = 45
	WEEK_OF_FLAME = 46
	WEEK_OF_WINDS = 47
	WEEK_OF_FOLLY = 48
	WEEK_OF_HONOR = 49
	WEEK_OF_DIPLOMACY = 50
	WEEK_OF_FORGERY = 51
	WEEK_OF_TRADE = 52
	WEEK_OF_MEDITATION = 53
	WEEK_OF_LIFE = 54
	WEEK_OF_CONJUNCTION = 55
	WEEK_OF_JEWELS = 56
	WEEK_OF_ALCHEMY = 57
	WEEK_OF_GOLD = 58
	WEEK_OF_FESTIVALS = 59
	WEEK_OF_HARVEST = 60
	WEEK_OF_IDLENESS = 61
	WEEK_OF_MAGIC = 62
	WEEK_OF_FEEBLENESS = 63
	WEEK_OF_SORROW = 64
	WEEK_OF_CHAOS = 65
	WEEK_OF_CALM = 66
	WEEK_OF_HOPE = 67
	WEEK_OF_WATER = 68
	WEEK_OF_FIRE = 69
	WEEK_OF_EARTH = 70
	WEEK_OF_AIR = 71
	WEEK_OF_FIRENICE = 72
	WEEK_OF_MIGHT = 73
	WEEK_OF_BALANCE = 74
	WEEK_OF_MIGHTNMAGIC = 75
	WEEK_OF_INFIRMITY = 76
	WEEK_OF_LIGHT = 77
	WEEK_OF_EVOCATION = 78
	WEEK_OF_ABJURATION = 79
	WEEK_OF_ALTERATION = 80
	WEEK_OF_CONJURATION = 81
	WEEK_OF_ETHER = 82
	WEEK_OF_TOUGHNESS = 83
	WEEK_OF_PEASANT = 84
	WEEK_OF_ARCHER = 85
	WEEK_OF_FOOTMAN = 86
	WEEK_OF_GRIFFIN = 87
	WEEK_OF_PRIEST = 88
	WEEK_OF_CAVALIER = 89
	WEEK_OF_ANGEL = 90
	WEEK_OF_GREMLIN = 91
	WEEK_OF_GARGOYLE = 92
	WEEK_OF_GOLEM = 93
	WEEK_OF_MAGI = 94
	WEEK_OF_GENIE = 95
	WEEK_OF_RAKSHASA = 96
	WEEK_OF_GIANT = 97
	WEEK_OF_PIXIE = 98
	WEEK_OF_WARDANCER = 99
	WEEK_OF_WOODELF = 100
	WEEK_OF_DRUID = 101
	WEEK_OF_UNICORN = 102
	WEEK_OF_TREANT = 103
	WEEK_OF_GREENDRAGON = 104
	WEEK_OF_IMP = 105
	WEEK_OF_DEMON = 106
	WEEK_OF_HELLHOUND = 107
	WEEK_OF_SUCCUBUS = 108
	WEEK_OF_NIGHTMARE = 109
	WEEK_OF_BALOR = 110
	WEEK_OF_DEVIL = 111
	WEEK_OF_ASSASSIN = 112
	WEEK_OF_WITCH = 113
	WEEK_OF_MINOTAUR = 114
	WEEK_OF_RIDER = 115
	WEEK_OF_HYDRA = 116
	WEEK_OF_MATRON = 117
	WEEK_OF_DRAGON = 118
	WEEK_OF_SKELETON = 119
	WEEK_OF_WALKINGDEAD = 120
	WEEK_OF_WIGHT = 121
	WEEK_OF_VAMPIRE = 122
	WEEK_OF_LICH = 123
	WEEK_OF_GHOST = 124
	WEEK_OF_BONEDRAGON = 125

	-- Animation Action Types
	--
	--INVISIBLE = 0
	IDLE = 1
	ONESHOT_STILL = 2
	ONESHOT = 3
	--MOVE = 4
	NON_ESSENTIAL = 5

	-- Monsters names filter
	MONSTER_NAME_SINGLE = 0
	MONSTER_NAME_MULTIPLE = 1
	MONSTER_NAMES_ALL = 2

	-- Disabled interactive objects modes
	DISABLED_DEFAULT = 0
	DISABLED_ATTACK = 1
	DISABLED_INTERACT = 2
	DISABLED_BLOCKED = 3

	-- Region Auto Action modes
	REGION_AUTOACTION_ON_ENTER = 1
	REGION_AUTOACTION_ON_EXIT = 2

	-- Region Auto Action enable variants
	REGION_AUTOACTION_OBJECT_NO_ACTION = -1
	REGION_AUTOACTION_OBJECT_DISABLE = 0
	REGION_AUTOACTION_OBJECT_ENABLE = 1

	-- Heroes Roles Modes
	--
	-- NOTE: for SetHeroRoleMode(heroName,roleMode) script commmand
	--
	HERO_ROLE_MODE_REGULAR = 0
	HERO_ROLE_MODE_FREEMAN = 1	-- always Freelancer
	HERO_ROLE_MODE_HERMIT  = 2	-- always Freelancer, never interact with other heroes

	--
	-- Players filtering constants (you can sum PLAYERFLT_1..8, but not PLAYERFLT_TEAM_1..8)
	--
	PLAYERFLT_1 = 1
	PLAYERFLT_2 = 2
	PLAYERFLT_3 = 4
	PLAYERFLT_4 = 8
	PLAYERFLT_5 = 16
	PLAYERFLT_6 = 32
	PLAYERFLT_7 = 64
	PLAYERFLT_8 = 128
	PLAYERFLT_ALL = 255
	PLAYERFLT_TEAM_1 = -1
	PLAYERFLT_TEAM_2 = -2
	PLAYERFLT_TEAM_3 = -3
	PLAYERFLT_TEAM_4 = -4
	PLAYERFLT_TEAM_5 = -5
	PLAYERFLT_TEAM_6 = -6
	PLAYERFLT_TEAM_7 = -7
	PLAYERFLT_TEAM_8 = -8

	--
	-- Players Teams constants
	--
	PLAYERS_TEAM_1 = 1
	PLAYERS_TEAM_2 = 2
	PLAYERS_TEAM_3 = 3
	PLAYERS_TEAM_4 = 4
	PLAYERS_TEAM_5 = 5
	PLAYERS_TEAM_6 = 6
	PLAYERS_TEAM_7 = 7
	PLAYERS_TEAM_8 = 8

	--
	-- Hero battle bonuses IDs
	--
	HERO_BATTLE_BONUS_LUCK = 0
	HERO_BATTLE_BONUS_MORALE = 1
	HERO_BATTLE_BONUS_ATTACK = 2
	HERO_BATTLE_BONUS_DEFENCE = 3
	HERO_BATTLE_BONUS_HITPOINTS = 4
	HERO_BATTLE_BONUS_INITIATIVE = 5
	HERO_BATTLE_BONUS_SPEED = 6


	FLYING_SIGN_TIME = 9

function createAdvmapAliases()
    --
    -- dumb command aliasing
    --
	names = GetAllNames
	GiveExpToLevel = LevelUpHero
    Exists = IsObjectExists
    GetObjectPos = GetObjectPosition
	SetObjectPos = SetObjectPosition
	CreateMob = CreateMonster
    GenerateMobs = GenerateMonsters
    KillMobs = RemoveAllMonsters
	CalcAverageTier = CalcAverageMonstersTier
	SetLight = SetAmbientLight
	SetCombatLight = SetCombatAmbientLight
    ShowFlyMessage = ShowFlyingSign
	Trigger = SetTrigger
    ExecConsoleCommand = consoleCmd
	GiveArtifact = GiveArtefact
end

MakeSyncCommandCallback = function(event_id)
	return function() mark_event(%event_id)	end
end

SyncCommand = function(command, arg, callback, saveName)
	if saveName == nil then
		saveName = ''
	end
	local event = make_event()
	command(arg, 'MakeSyncCommandCallback(' .. event .. ')', saveName)
	wait_event(event)
	if callback and callback ~= '' then
		parse(callback .. '()')()
	end
end

if MessageBoxInt then
	MessageBox = function(name, callback) SyncCommand(MessageBoxInt, name, callback) end
end
if QuestionBoxInt then
	QuestionBox = QuestionBoxInt
--	QuestionBox = function(name, callback) SyncCommand(QuestionBoxInt, name, callback) end
end
if StartCutSceneInt then
	StartCutScene = function(name, callback, saveName) SyncCommand(StartCutSceneInt, name, callback, saveName) end
end
if StartDialogSceneInt then
	StartDialogScene = function(name, callback, saveName) SyncCommand(StartDialogSceneInt, name, callback, saveName) end
end


LOAD_SOURCES = 0
dofile("/scripts/advmap-common.lua")
repeat sleep(1) until LOAD_SOURCES == 1

dofile("/scripts/advmap-manager.lua")
